blog_home:
    path: /
    defaults: { _controller: SimpleBlogBundle:Post:list }
    methods: [GET]
    requirements:
        id: \d+

blog_post_new_form:
    path: /post/new
    defaults: { _controller: SimpleBlogBundle:Post:newForm }
    methods: [GET]

blog_post_new:
    path: /post/new
    defaults: { _controller: SimpleBlogBundle:Post:new }
    methods: [POST]

blog_post_view:
    path: /post/{id}
    defaults: { _controller: SimpleBlogBundle:Post:view }
    methods: [GET]
    requirements:
        id: \d+

blog_post_edit_form:
    path: /post/{id}/edit
    defaults: { _controller: SimpleBlogBundle:Post:editForm }
    methods: [GET]
    requirements:
        id: \d+

blog_post_update:
    path: /post/{id}
    defaults: { _controller: SimpleBlogBundle:Post:update }
    methods: [POST]
    requirements:
        id: \d+

blog_post_delete:
    path: /post/{id}
    defaults: { _controller: SimpleBlogBundle:Post:delete }
    methods: [DELETE]
    requirements:
        id: \d+
